### ISSUE TITLE
Setup CI/CD pipeline with Travis CI

### ISSUE THREAD

**Issue by suraneti** [kulapio/libra-wallet-poc#24]
Should we set up CI/CD for each pull request?

**Comment by totiz** [comment]
Yeah I think so we should setup CI/CD for all the projects if you can help on this please go ahead, it's free right?.

**Comment by suraneti** [comment]
@totiz It's free for a public repo. I've set for libra-service and PR.

**Comment by totiz** [comment]
@suraneti Ok, I'm on testing why tx3 error? will merge soon.

**Comment by suraneti** [comment]
**TODO**

- [x] Create `.travis.yml` file.
- [ ] Setup unit test all components.
- [ ] Connect with travis-ci from origin repo.

**Comment by totiz** [comment]
@suraneti What should we do next? please consult me to setup travis-ci

**Comment by suraneti** [comment]
@totiz OK, I'll contact you about Travis-ci integration.

**Comment by totiz** [comment]
Nice, now working
